README.md
REQUIRE
src/SQLite.jl
src/UDF.jl
src/show.jl
test/runtests.jl

Fixes all the compatibility issues necessary to get working on 0.4.
The only breaking change is the rename of `drop` to `droptable`, to avoid conflict with method in Base.

get working on 0.4

---

src/SQLite.jl
src/UDF.jl
src/api.jl
src/show.jl

1. Renames of deprecated symbols
2. `string(regexp)` now returns "SQLite.regexp", so pass "regexp" as a name explicitly into `register`.

Fixes for julia 0.4

---

src/SQLite.jl
src/Sink.jl
src/Source.jl

Defines `esc_id` and `esc_str` (currently unused) for escaping identifiers in SQL queries. I've only updated the new interface so far.

escape identifiers in SQL statements

---

src/Sink.jl

travis may fail due to untagged versions on dependencies (DataStreams and CSV)

fixes #100

---

REQUIRE
deps/build.jl
src/SQLite.jl

There were errors caused by `using LegacyStrings` without having LegacyStrings in the REQUIRE. I also fixed the deprecation warnings for the OS checking blocks.

Fix errors and deprecation warnings

---

README.md
appveyor.yml
src/SQLite.jl

given the presence of the `@NULLCHECK` macros I don't see why this would change anything, but I might be missing something

see if avoiding double-finalizing fixes win32 access violation

---

src/Sink.jl

Fixes #136
`sqlitetype` changed to assign `{T} NOT NULL` for julia types that are not a `Union{Missing, T}` type and `{T}` to types that are. For example, 
```julia
julia> SQLite.sqlitetype(Union{Missing, Float64})     # Used to return "BLOB"
"REAL"
julia> SQLite.sqlitetype(Float64)       # Used to return "REAL"
"REAL NOT NULL"
```

Better sqlite types for Union{Missing, T}

---

.travis.yml
docs/Project.toml
docs/make.jl

Hi!
I found this on travis logs for SQLite:
```
$ julia -e 'using Pkg; cd(Pkg.dir("SQLite")); include(joinpath("docs", "make.jl"))'
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import SQLite; joinpath(dirname(pathof(SQLite)), "..", paths...)`.
└ @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:480
┌ Warning: `format = :html` is deprecated, use `format = Documenter.HTML()` instead.
│   caller = ip:0x0
└ @ Core :-1
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: ExpandTemplates: expanding markdown templates.
[ Info: CrossReferences: building cross-references.
[ Info: CheckDocument: running document checks.
┌ Warning: 16 docstrings potentially missing:
│ 
│     SQLite.tables :: Union{Tuple{DB}, …
```

fix docs build

---

docs/make.jl

So, it didn't work out, but it is almost there! :smile: 
The repo URL is wrong, so this PR should fix that.
Another thing you need to do is to set the `DOCUMENTER_KEY` environment variable in travis, as described in https://juliadocs.github.io/Documenter.jl/stable/man/hosting/.

fix docs deployment

---

docs/src/index.md

At first read, I didn't realize these were all separate possibilities since they appeared on one line on the web docs:

Add spaces to parameter list for clarity

---

src/tables.jl
test/runtests.jl

I chnaged the signature of the DBInterface.prepare function to receive AbstractString istead of Strings. I faced the following error:
```
julia> using SQLite
julia> using DBInterface
julia> a = SQLite.DB("a")
julia> DBInterface.prepare(a, strip("   SELECT * FROM table  "))
ERROR: DBInterface.NotImplementedError("`DBInterface.prepare` not implemented for `SQLite.DB`")
Stacktrace:
[1] prepare(::SQLite.DB, ::SubString{String}) at /home/luciano/.julia/packages/DBInterface/EUwXt/src/DBInterface.jl:41
[2] top-level scope at REPL[10]:1
```

Fix signature of DBInterface.prepare

---

src/SQLite.jl
src/api.jl
test/runtests.jl

This option is often set when connecting to the db, not sure what's the best way to expose this functionality, here is a suggestion for adding a function to set it later.
https://www.sqlite.org/c3ref/busy_timeout.html

Set busy_timeout

---

Project.toml
src/tables.jl
test/runtests.jl

The PR implements adds `DBInterface.close!(::Query)` required by `DBInterface.execute(f, stmt)` introduced in JuliaDatabases/DBInterface.jl#35 and adds tests to make sure that `DBIntreface.execute(f, ...)` methods work.

Support DBInterface.execute(f, stmt) method

---

src/SQLite.jl
src/tables.jl
test/runtests.jl

At the moment if the *Query* is empty, its scheme would be empty too, although the *Query.names* and *Query.types* are already properly initialized. This is inconvenient, since the user code then would have to check whether the result is empty before accessing any columns.
The PR fixes that: if the *Query* is empty, the scheme would be based on *Query.names* and *Query.types*, otherwise it will fall back to using the values of the actual result.
Also the *Base.isempty(::Query)* is added (needed for the schema fix).
And *juliatype(string)* is taught to recognize more declared column types (e.g. in future we might support *DATETIME* properly).

Correct scheme for empty Query

---

src/SQLite.jl

This allows queries that take less named parameters than the length of the given NamedTuple to still bind those names that exist. Enables reuse of existing NamedTuples for multiple queries.
This came up on Slack and it seemed like an easy fix.

Relax NamedTuple length requirements for queries with named parameters

---

src/SQLite.jl
test/runtests.jl

Suppresses type conversion warnings mentioned in #219 and #231.
I've also clarified the warning message, so people can see which Julia types will be actually used for the data.
However, the types logic in SQLite is more complex (see [SQLite types docs](https://www.sqlite.org/datatype3.html)).
E.g. *NUMERIC* could be integer or float depending on the actual values stored, and when importing data into julia the actual Julia column type may differ from what `juliatype()` provides.

Improve juliatype()

---

src/SQLite.jl
test/runtests.jl

Fixes https://github.com/JuliaDatabases/SQLite.jl/issues/207. The issue
here was in our translation from sqlite type to Julia type, we were
using `Int`, though in the `sqlitevalue` function that actually
retrieved the value from the database, we used `sqlite3_column_int64`.
This change just ensures that even in 32-bit systems, we'll return
values as Int64, avoiding issues like the `RANDOM()` sqlite function,
which returns an Int64 value.

Ensure bit integer values are returned as Int64

---

src/SQLite.jl
test/runtests.jl

Related to this [issue](https://github.com/JuliaDatabases/SQLite.jl/issues/221#issuecomment-802575262).
I added a method for `bind!` function, and it solves my problem seen in previous MWE, but do I need to also add something on `sqlitetype` function (and its related test)?
Currently, with only `bind!` added, I have this:
```julia
julia> SQLite.sqlitetype(Missing)
"NULL"
julia> SQLite.sqlitetype(Nothing)
"BLOB NOT NULL"
```
Tell me if further modifications are needed.

Handle nothing as missing in binding.

---

src/SQLite.jl
src/tables.jl
test/runtests.jl

Fixes #253. Most data formats have requirements around column name
uniqueness, including DataFrames.jl. The proposed changes here ensure
query result columns are unique by default, while still allowing column
names to be duplicated if they pass `allowduplicates=true` to
`DBInterface.execute`.

By default, make query column names unique

---

src/api.jl
test/runtests.jl

Not sure why "+1" was there, but it lead to an extra nul byte at the end.

fix string outputs from UDF

---

src/tables.jl
test/runtests.jl

Fixes #251 amongst other issues. This PR makes `SQLite.Row` explicitly
error when values are attempted to be accessed and it's not the
currently iterated row. It borrows the idea from the MySQL.jl package,
which as a similar "sync" of row numbers between the `Row` and `Query`
objects.

Ensure rows are only valid while currently being iterated

---

src/SQLite.jl
src/api.jl
src/tables.jl

SQLite3 provides `sqlite3_expanded_sql()` to retrieve the _as-bound_ statement text; this makes it possible to report the exact failing INSERT when `load!()` fails, e.g. due to a `PRIMARY KEY` violation.
I found it very useful when debugging all the various ways a pre-existing data source violated its own nominal schema.

Report the failing INSERT when `load!()` errors

---

src/SQLite.jl
src/tables.jl
test/runtests.jl

@quinnj as discussed.
Resolves #209. 
Note: moved  few tests from typeof -> isa, let me know if I should nix it :)
TODO: need to add a test for db without any tables

Add DBTables type

---

src/SQLite.jl
test/runtests.jl

Remove warning in juliatype

---

src/SQLite.jl

We're getting method-overwritten warnings on master

Fix warnings on master

---

src/tables.jl
test/runtests.jl

[#263](https://github.com/JuliaDatabases/SQLite.jl/pull/263) allows the choice between INSERT or REPLACE for the load! function. However, there are several other [constraint conflict resolution algorithms](https://sqlite.org/lang_conflict.html) listed in the SQLite specification, which could also be supported.
This pull request adds another keyword argument `or::Union{String, Nothing}` to the load! function, which is set to `nothing` by default. Valid values include `nothing`, "ROLLBACK", "ABORT", "FAIL", "IGNORE" and "REPLACE". For backwards compatibility, the `replace` keyword argument is left intact. If the new argument is set to its default value of `nothing`, the old keyword arbitrates between INSERT and REPLACE.

Allow selection of constraint conflict resolution algorithm in SQLite.load!

---

src/SQLite.jl

Fixes https://github.com/JuliaDatabases/SQLite.jl/issues/306.
The core issue here is that when we `bind!` some values to an insert statement, the _cconvert_ed value needs to remain valid (i.e. not GC-able) until we execute the insert statement in `sqlite3_step`. In each `SQLite.Stmt`, we have a `params` field for storing these values, but we weren't accounting for the fact that some values, (in the original issue case, InlineStrings), may be `cconvert`ed to a different value when they're actually bound, and it's the cconverted value that we need to store in `params` until the statement is executed.

Manually preserve cconvert values until sqlite3_step

---

docs/src/index.md
src/UDF.jl
test/runtests.jl

Address https://github.com/JuliaDatabases/SQLite.jl/issues/317 and some reformatting changes.

Deprecate @sr_str macro by Base.@raw_str and suggest users to switch.

---

src/SQLite.jl
src/UDF.jl

Attemp to fix https://github.com/JuliaDatabases/SQLite.jl/issues/335

Avoid using cfunction closure

---

src/SQLite.jl
test/runtests.jl

This allows zero-copy writes e.g. for ReinterpretArrays.
Do you want this to be tested explicitly?

relax bind! Vector{UInt8} -> AbstractVector{UInt8}
